spring.main.allow-circular-references=true

# =========================
# DATABASE
# =========================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.connectionTimeout=60000
spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.maximumPoolSize=3
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.keepaliveTime=30000

# =========================
# HIBERNATE / JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=expense_tracker
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.defer-datasource-initialization=true

# =========================
# SQL INIT
# =========================

spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql

# =========================
# SERVER
# =========================

server.port=${PORT:8080}
server.address=0.0.0.0

# =========================
# ACTUATOR / HEALTH
# =========================

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# =========================
# JWT
# =========================

app.jwtSecret=${APP_JWT_SECRET:======================expense=tracker=mywallet===========================}
app.jwtExpirationMs=${APP_JWT_EXPIRATION_MS:86400000}

# =========================
# MAIL
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# APP CONFIG
# =========================

app.verificationCodeExpirationMs=${APP_VERIFICATION_CODE_EXPIRATION_MS:60000}

app.user.profile.upload.dir=${APP_USER_PROFILE_UPLOAD_DIR:./uploads/user/profile}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB